config/routes.rb
Rails.application.routes.draw do

  get "/sessions/new", to: "sessions#new", as: :sign_in
  get "/auth/failure", to: "identities#authentication_failure"
  post "/auth/:provider/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy", as: :sign_out

  resources :identities, :users, :movies

  resources :movies do
      collection  do
        post :edit_individual
        put  :update_individual
      end
   end

  root to: "home#index"

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :find_movie

  def index
    @movies = Movie.order(:release_date)
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def edit_individual
    @movies = Movie.find(params[:movie_ids])
  end

  def update_individual
    @movies = Movie.update(params[:movies].keys, params[:movies].values).reject { |p| p.errors.empty? }
    if @movies.empty?
      flash[:notice] = "Movies updated"
      redirect_to movies_path
    else
      render :action => "edit_individual"
    end
  end

  def create
    @movie = Movie.new(movie_params)
    i = Imdb::Movie.new("#{@movie.movie_name}")
    if @movie.save
      @movie.movie_description = i.title
      @movie.release_date = i.release_date
      @movie.movie_plot = i.plot_summary
      @movie.movie_rating = i.mpaa_rating
      @movie.imdb_url = i.trailer_url
      @movie.save!
      redirect_to movies_path, notice: %Q[Saved "#{@movie.movie_name}" successfully.]
    else
      render :new
    end
  end

  def update
    if @movie.update_attributes(movie_params)
      i = Imdb::Movie.new("#{@movie.movie_name}")
      @movie.movie_description = i.title
      @movie.release_date = i.release_date
      @movie.movie_plot = i.plot_summary
      @movie.movie_rating = i.mpaa_rating
      @movie.imdb_url = i.trailer_url
      @movie.save!
      redirect_to movie_path(@movie), notice: %Q[Updated "#{@movie.movie_name}" successfully.]
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private

  def find_movie
    @movie = Movie.find(params[:id]) if params[:id]
  end

  def movie_params
    params.require(:movie).permit(:movie_name, :movie_poster, :movie_description, :release_date, :imdb_url, :boxoffice_earnings, :movie_plot, :movie_rating)
  end
end

app/views/movies/_fields.html.erb
<% if params[:field].blank? || params[:field] == "movie_description" %>
<p>
  <%= f.label :movie_description %><br />
  <%= f.text_field :movie_description %>
</p>
<% end %>
<% if params[:field].blank? || params[:field] == "boxoffice_earnings" %>
<p>
  <%= f.label :boxoffice_earnings %><br />
  <%= f.text_field :boxoffice_earnings %>
</p>
<% end %>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <%= content_tag :div, class: "alert-box alert" do %>
    <h4><%= pluralize @movie.errors.count, "error" %> kept this form from submitting:</h4>
    <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end if @movie.errors.any? %>
  <%= f.label "Movie number" %><small>To find this, go to the page on IMDB for the movie. In the URL after "tt" will be the number. For example, Warcraft is 0803096</small>
  <%= f.text_field :movie_name %>
  <%= f.label :movie_poster %>
  <%= f.text_field :movie_poster %>
  <%= f.label :boxoffice_earnings %>
  <%= f.number_field :boxoffice_earnings %>
  <%= f.submit nil, class: "button radius" %>
<% end %>

app/views/movies/_movie.html.erb
	  <div class="columns">
	<%= link_to movie_path(movie) do %>
	  	<%= image_tag movie.movie_poster, alt: movie.movie_description, style: "max-height: 175px; width: auto;" %>
		  <h5><%= movie.movie_description %><br/>
		  <small><%= movie.release_date.try(:strftime, "%B %d") %></small>
	<% end %>
	  </div>

app/views/movies/edit.html.erb
<% content_for :title, "Edit #{@movie.movie_name}" %>
<div class="columns">
	<h1>Edit <%= @movie.movie_description %></h1>
	<%= render "form" %>
</div>

app/views/movies/edit_individual.html.erb
<% form_tag update_individual_movies_path, :method => :put do %>
  <% for movie in @movies %>
    <% fields_for "movies[]", movie do |f| %>
      <h2><%=h movie.movie_description %></h2>
      <%= render "fields", :f => f %>
    <% end %>
  <% end %>
  <p><%= submit_tag "Submit" %></p>
<% end %>

app/views/movies/index.html.erb
<% content_for :title, "Movies" %>
<div class="columns">
	<h1>Movies</h1>
	<% if current_user.has_role?(:admin) %>
	<p><%= link_to "Create a new movie", new_movie_path, class: "button radius" %></p>
	<% end %>

	<div class="medium-8 columns">
		<div class="row medium-up-3 large-up-4">
			<%= render @movies %>
		</div>
	</div>

	<DIV CLASS="medium-4 columns show-for-medium">
		<h5>My current list</h5>
		<ul class="wtx-movie-list no-bullet">
			<li><strong class="place-movies-all">1.</strong> <%= current_user.movie_one %></li>
			<li><strong class="place-movies-all">2.</strong> <%= current_user.movie_two %></li>
			<li><strong class="place-movies-all">3.</strong> <%= current_user.movie_three %></li>
			<li><strong class="place-movies-all">4.</strong> <%= current_user.movie_four %></li>
			<li><strong class="place-movies-all">5.</strong> <%= current_user.movie_five %></li>
			<li><strong class="place-movies-all">6.</strong> <%= current_user.movie_six %></li>
			<li><strong class="place-movies-all">7.</strong> <%= current_user.movie_seven %></li>
			<li><strong class="place-movies-all">8.</strong> <%= current_user.movie_eight %></li>
			<li><strong class="place-movies-all">9.</strong> <%= current_user.movie_nine %></li>
			<li><strong class="place-movies-all">10.</strong> <%= current_user.movie_ten %></li>
			<li><strong class="place-movies-all">Darkhorse 1.</strong> <%= current_user.movie_darkhorse_one %></li>
			<li><strong class="place-movies-all">Darkhorse 2.</strong> <%= current_user.movie_darkhorse_two %></li>
			<li><strong class="place-movies-all">Darkhorse 3.</strong> <%= current_user.movie_darkhorse_three %></li>
		</ul>
		<% if current_user.has_role?(:admin) %>
			<%= link_to "Edit #{current_user.first_name}'s List", edit_user_path(@current_user), class: 'button small radius' %>
		<% end %>
	</DIV>
</div>

<% if current_user.has_role?(:admin) %>
<p>ignore for now</p>
	<%= form_tag edit_individual_movies_path do %>
	  <table>
	    <tr>
	      <th></th>
	      <th>Name</th>
	      <th>Box Office</th>
	    </tr>
	  <% for movie in @movies %>
	    <tr>
	      <td><%= check_box_tag "movie_ids[]", movie.id %></td>
	      <td><%=h movie.movie_description %></td>
	      <td><%=h movie.boxoffice_earnings %></td>
	      <td><%= link_to "Edit", edit_movie_path(movie) %></td>
	      <td><%= link_to "Destroy", movie, :confirm => 'Are you sure?', :method => :delete %></td>
	    </tr>
	  <% end %>
	  </table>
	  <p>
	    <%= select_tag :field, options_for_select([["All Fields", ""], ["Movie", "movie_description"], ["Box Office", "boxoffice_earnings"]]) %>
	    <%= submit_tag "Edit Checked" %>
	  </p>
	<% end %>
<% end %>

app/views/movies/new.html.erb
<% content_for :title, "New movie" %>
<h1>New movie</h1>
<%= render "form" %>

app/views/movies/show.html.erb
<%= content_for :title, @movie.movie_description %>
<h1><%= @movie.movie_description %></h1>


<div class="row">
  <div class="medium-4 columns">
    <%= image_tag @movie.movie_poster, alt: @movie.movie_description %>
  </div>
  <div class="medium-8 columns">
    <strong>Description:</strong> <br/>
    <div class="movie-description-html"><%= raw(@movie.movie_plot) %></div><br/>
    <strong>Rating:</strong> <%= @movie.movie_rating %><br/>
    <strong>Release date:</strong> <%= @movie.release_date.try(:strftime, "%B %d") %>
    <%= content_tag :p do %>
      <strong>Trailer link:</strong> <%= link_to @movie.imdb_url, target: "_blank"%>
    <% end if @movie.imdb_url.present?%>
    <%= content_tag :p do %>
      <strong>Box office earnings:</strong> <%= number_to_currency @movie.boxoffice_earnings, precision: 0 %>
    <% end if @movie.boxoffice_earnings > 0 %>
    <% if current_user.has_role?(:admin) %>
      <%= link_to "Edit #{current_user.first_name}'s list", edit_user_path(current_user), class: "button radius" %>
      <p>
        <%= link_to edit_movie_path(@movie), class: "button radius" do %>
          <span class="fa fa-pencil"></span>
          Edit
        <% end %>
        <%= link_to movie_path(@movie), data: {confirm: %Q[Are you sure you want to delete #{@movie.movie_description}? This cannot be undone!]}, method: :delete, class: "button radius alert" do %>
        <span class="fa fa-trash"></span>
        Delete
        <% end %>
      <% end %>
    </p>
  </div>
</div>