config/routes.rb
Rails.application.routes.draw do

  get "/sessions/new", to: "sessions#new", as: :sign_in
  get "/auth/failure", to: "identities#authentication_failure"
  post "/auth/:provider/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy", as: :sign_out

  resources :identities, :users, :movies

  resources :movies do
      collection  do
        post :edit_individual
        put  :update_individual
      end
   end

  root to: "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def authenticate!
    unless current_user
      redirect_to sign_in_path
    end
  end
  helper_method :authenticate!

  def current_user
    @current_user ||= User.find_by(auth_token: cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.humanize(capitalize: false)
    flash[:error] = "The #{policy_name.underscore.humanize} prohibits you from performing #{exception.query} on #{exception.record}."
    redirect_to request.referrer || root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = nil)
    if page_title.present?
      "Summer Movie Game - #{page_title}"
    else
      "Summer Movie Game"
    end
  end
end

app/views/application/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, data: { alert: "" }, class: "alert-box #{name}" do %>
    <%= msg %>
    <%= link_to "X", nil, class: "close" %>
  <% end %>
<% end %>

app/views/application/_site_footer.html.erb
<footer class="site-footer">
  <hr/>
  <div class="medium-6 columns">
    <p>&copy; <%= Time.now.year %> Wavetronix LLC.</p>
  </div>
  <div class="medium-6 columns end text-right show-for-medium">
    <p>
      <% if current_user %>
        <%= current_user.name %>
      <% else %>
        <%= link_to root_path do %>
          <%= icon('sign-in', 'Sign In', class: 'strong') %>
        <% end %>
      <% end %>
    </p>
  </div>
</footer>

app/views/application/_site_header.html.erb
<header>
  <div class="header-title">
    <p>Summer Movie Game</p>
  </div>
    <ul>
      <% if current_user %>
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "movies", movies_path %></li>
        <li><%= link_to "#{current_user.first_name}'s list", current_user %></li>
        <li><%= link_to "all lists", users_path %></li>
        <li><%= link_to "sign out", sign_out_path %></li>
      <% else %>
        <li><%= link_to "sign in", sign_in_path %></li>
      <% end %>
    </ul>
    <hr/>
</header>